name: GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
#  pull_request:
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    env:
      DTC_HEADLESS: true
    steps:
      - uses: actions/checkout@v2
      - name: exportExcel
        run: ./dtcw exportExcel
      - name: generateSite
        run: ./dtcw generateSite
      - name: generatePdf
        run: ./dtcw generatePdf
      - name: htmlSanityCheck
        run: ./dtcw htmlSanityCheck
      - name: copyToPublic
        run: cp -r ./build/microsite/output ./public && cp -r ./build/report/htmlchecks ./public && cp -r ./build/pdf ./public
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
#        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

